#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

#define SCREENSAVE_DELAY 12000 //configure how long to wait after last activity. 120000ms = 2 mins

enum custom_keycodes {
    NO_SLEEP = SAFE_RANGE,  //custom macro key.  turns on screensaver mode
    //other macros,
    //...
};


bool stop_screensaver = false;     //screensaver mode status
uint32_t last_activity_timer = 0;

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    if (record->event.pressed)
        stop_screensaver = false;  //turn off screensaver mode on any keypress

    switch (keycode) {
        case NO_SLEEP:
            if (record->event.pressed) {               //if NO_SLEEP is pressed
                stop_screensaver = true;               //turn on screensaver mode
                last_activity_timer = timer_read32();  //reset timer
            }
            break;
        //other macros...
    }
    return true;
}


void matrix_scan_user(void) {
    if (stop_screensaver) {                                             //if screensaver mode is active
        if (timer_elapsed32(last_activity_timer) > SCREENSAVE_DELAY) {  //and no key has been pressed in more than SCREENSAVE_DELAY ms
            tap_code16(KC_F23);                                         //  tap F13
                                                                            tap_code(KC_MS_UP);

            last_activity_timer = timer_read32();                       //  reset last_activity_timer
        }
    }
}
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_5x6(KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_BSPC, KC_GRV, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_MINS, KC_CAPS, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_BSLS, KC_LBRC, KC_RBRC, KC_PLUS, KC_EQL, MO(1), KC_SPC, KC_NO, KC_NO, KC_LALT, KC_LGUI, KC_NO, KC_BSPC, KC_LCTL, KC_F13, KC_RCTL, KC_LSFT),
	[1] = LAYOUT_5x6(KC_TILD, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_TRNS, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_F12, KC_TAB, KC_GRV, KC_WH_D, KC_WH_U, KC_QUOT, KC_LPRN, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_MINS, KC_VOLU, NO_SLEEP, KC_TRNS, KC_LCBR, KC_LBRC, KC_LPRN, KC_BSLS, KC_SLSH, KC_RPRN, KC_RBRC, KC_RCBR, KC_EQL, KC_VOLD, KC_TRNS, KC_PSCR, KC_TRNS, KC_P0, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS)
};


#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][2] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
enum combos {
  JK_ESC,
  MC_TAB,
  DF_ENT,
  CV_UND
};

const uint16_t PROGMEM jk_combo[] = {KC_J, KC_K, COMBO_END};
const uint16_t PROGMEM mc_combo[] = {KC_M, KC_COMMA, COMBO_END};
const uint16_t PROGMEM df_combo[] = {KC_D, KC_F, COMBO_END};
const uint16_t PROGMEM cv_combo[] = {KC_C, KC_V, COMBO_END};

combo_t key_combos[] = {
  [JK_ESC] = COMBO(jk_combo, KC_ESC),
  [MC_TAB] = COMBO(mc_combo, KC_TAB),
  [DF_ENT] = COMBO(df_combo, KC_ENT),
  [CV_UND] = COMBO(cv_combo, KC_UNDERSCORE),
};


